- src/components/ColumnEditor/ColumnEditor.test.tsx
- src/components/ColumnEditor/ColumnEditor.tsx
- src/components/ColumnsEditor/ColumnsEditor.tsx
- src/components/Table/Table.tsx
- src/components/Table/components/TableHeaderCell/TableHeaderCell.styles.ts
- src/components/Table/components/TableHeaderCell/TableHeaderCell.tsx
- src/constants.ts
- src/hooks/useTable.test.tsx
- src/hooks/useTable.tsx
- src/migration.ts
- src/types/panel.ts
- src/utils/test.ts
> Add sorting

- provisioning/dashboards/panels.json
- src/components/CellRenderer/CellRenderer.test.tsx
- src/components/CellRenderer/CellRenderer.tsx
- src/components/CellRenderer/DefaultCellRenderer.tsx
- src/components/ColumnEditor/ColumnEditor.test.tsx
- src/components/ColumnEditor/ColumnEditor.tsx
- src/components/ColumnsEditor/ColumnsEditor.tsx
- src/components/Table/Table.tsx
- src/components/Table/components/TableRow/TableRow.styles.ts
- src/components/Table/components/TableRow/TableRow.test.tsx
- src/components/Table/components/TableRow/TableRow.tsx
- src/components/Table/components/TableRow/index.ts
- src/components/Table/components/index.ts
- src/constants.ts
- src/hooks/useTable.test.tsx
- src/hooks/useTable.tsx
- src/migration.ts
- src/types/panel.ts
- src/types/table.ts
- src/utils/table.test.ts
- src/utils/test.ts
> Add Colored Background Column type

- CHANGELOG.md
- provisioning/dashboards/panels.json
- src/__mocks__/@grafana/data.ts
- src/__mocks__/@grafana/runtime.ts
- src/components/ColumnEditor/ColumnEditor.test.tsx
- src/components/ColumnEditor/ColumnEditor.tsx
- src/components/ColumnsEditor/ColumnsEditor.tsx
- src/components/Table/Table.styles.ts
- src/components/Table/Table.test.tsx
- src/components/Table/Table.tsx
- src/constants.ts
- src/hooks/useTable.test.tsx
- src/hooks/useTable.tsx
- src/migration.ts
- src/types/panel.ts
- src/utils/table.test.ts
- src/utils/table.ts
- src/utils/test.ts
> Add table Footer

- CHANGELOG.md
- package-lock.json
- provisioning/dashboards/devices.json
- src/components/ColumnEditor/ColumnEditor.test.tsx
- src/components/ColumnEditor/ColumnEditor.tsx
- src/components/ColumnEditor/components/EditableColumnEditor/components/QueryOptionsEditor/QueryOptionsEditor.test.tsx
- src/components/ColumnEditor/components/EditableColumnEditor/components/QueryOptionsEditor/QueryOptionsEditor.tsx
- src/components/ColumnsEditor/ColumnsEditor.test.tsx
- src/components/ColumnsEditor/ColumnsEditor.tsx
- src/components/FieldPicker/FieldPicker.test.tsx
- src/components/FieldPicker/FieldPicker.tsx
- src/components/FieldPicker/index.ts
- src/components/FieldPicker/utils.ts
- src/components/index.ts
- src/constants.ts
- src/hooks/useTable.tsx
- src/types/panel.ts
- src/utils/permission.test.ts
- src/utils/permission.ts
- src/utils/test.ts
> Add edit permission based on query

- CHANGELOG.md
- provisioning/dashboards/panels.json
- src/components/ColumnEditor/ColumnEditor.test.tsx
- src/components/ColumnEditor/ColumnEditor.tsx
- src/components/ColumnsEditor/ColumnsEditor.tsx
- src/components/Table/Table.styles.ts
- src/components/Table/Table.test.tsx
- src/components/Table/Table.tsx
- src/components/Table/components/TableRow/TableRow.test.tsx
- src/components/Table/components/TableRow/TableRow.tsx
- src/constants.ts
- src/hooks/useTable.test.tsx
- src/hooks/useTable.tsx
- src/migration.ts
- src/types/panel.ts
- src/utils/test.ts
> Add functionality to pin columns

- CHANGELOG.md
- src/components/TablePanel/TablePanel.tsx
> Add reset table state on tab change

- CHANGELOG.md
- package.json
- provisioning/dashboards/panels.json
- src/components/Table/components/AggregatedCellRenderer/AggregatedCellRenderer.test.tsx
- src/components/Table/components/AggregatedCellRenderer/AggregatedCellRenderer.tsx
- src/components/Table/components/AggregatedCellRenderer/index.ts
- src/components/Table/components/index.ts
- src/components/Table/index.ts
- src/constants.ts
- src/hooks/useTable.tsx
> Update aggregated cell to support Standard Options

- provisioning/dashboards/data-links.json
- provisioning/dashboards/devices.json
- provisioning/dashboards/query-based.json
- src/components/TablePanel/TablePanel.test.tsx
- src/components/TablePanel/TablePanel.tsx
- src/components/editors/TablesEditor/components/TableEditor/components/ColumnsEditor/ColumnsEditor.test.tsx
- src/components/editors/TablesEditor/components/TableEditor/components/ColumnsEditor/ColumnsEditor.tsx
- src/constants.ts
- src/migration.ts
- src/types/panel.ts
- src/utils/test.ts
- test/panel.spec.ts
- test/utils/table.ts
> Allow to show/hide columns

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/editors/NestedObjectsEditor/components/NestedObjectEditor/components/NestedObjectCardsControl/components/NestedObjectCardsItem/NestedObjectCardsItem.tsx
Code editor updated according to changes in [PR67](https://github.com/VolkovLabs/business-packages/pull/67)
> Update Autosize Code Editor toolbar

- CHANGELOG.md
- src/components/editors/NestedObjectsEditor/components/NestedObjectEditor/components/NestedObjectCardsControl/components/NestedObjectCardContent/NestedObjectCardContent.tsx
> Add sanitizing html content

- CHANGELOG.md
- src/components/editors/NestedObjectsEditor/components/NestedObjectEditor/components/NestedObjectCardsControl/components/NestedObjectCardsItem/NestedObjectCardsItem.tsx
> Fix escaping new lines for content edit

- CHANGELOG.md
- src/components/TablePanel/TablePanel.test.tsx
- src/components/TablePanel/TablePanel.tsx
- src/components/editors/TablesEditor/components/TableEditor/components/ColumnsEditor/components/ColumnEditor/ColumnEditor.tsx
- src/hooks/useTable.test.tsx
- src/hooks/useTable.tsx
> Add data for hidden columns to payload

- src/components/editors/EditableColumnEditor/EditableColumnEditor.tsx
- src/components/editors/EditableColumnEditor/EditableColumnEditorsRegistry.test.tsx
- src/components/editors/EditableColumnEditor/EditableColumnEditorsRegistry.tsx
- src/components/editors/TablesEditor/components/TableEditor/components/ColumnsEditor/components/ColumnEditor/ColumnEditor.tsx
- src/constants.ts
- src/types/column-editor.ts
> Added Textarea column editor type

- CHANGELOG.md
- package-lock.json
- package.json
- src/hooks/useTable.tsx
- test/panel.spec.ts
- test/utils/table.ts
> Add replaceVariables to column header

- CHANGELOG.md
- provisioning/dashboards/panels.json
- provisioning/dashboards/wrap.json
- src/components/Table/Table.tsx
- src/components/Table/components/TableHeaderCell/TableHeaderCell.tsx
- src/components/Table/components/TableRow/TableRow.tsx
- src/components/editors/TablesEditor/components/TableEditor/components/ColumnsEditor/components/ColumnEditor/ColumnEditor.tsx
> Update text wrap

- CHANGELOG.md
- package.json
- provisioning/dashboards/panels.json
- src/components/Table/components/CellRenderer/CellRenderer.test.tsx
- src/components/Table/components/CellRenderer/CellRenderer.tsx
- src/components/Table/components/CellRenderer/LayoutCellRenderer.test.tsx
- src/components/Table/components/CellRenderer/LayoutCellRenderer.tsx
- src/components/editors/TablesEditor/components/TableEditor/components/ColumnsEditor/components/ColumnEditor/ColumnEditor.tsx
- src/constants.ts
- src/types/table.ts
> Add Sanitized HTML and Markdown column type

- CHANGELOG.md
- src/components/editors/DatasourceEditor/DatasourceEditor.test.tsx
- src/components/editors/DatasourceEditor/DatasourceEditor.tsx
- src/components/editors/DatasourcePayloadEditor/DatasourcePayloadEditor.test.tsx
- src/components/editors/DatasourcePayloadEditor/DatasourcePayloadEditor.tsx
- src/components/editors/RequestEditor/RequestEditor.tsx
- src/migration.test.ts
- src/migration.ts
> Update data source name to id

- CHANGELOG.md
- README.md
- provisioning/dashboards/panels.json
- src/components/Table/Table.test.tsx
- src/components/Table/Table.tsx
- src/components/TablePanel/TablePanel.tsx
- src/components/editors/TablesEditor/TablesEditor.test.tsx
- src/components/editors/TablesEditor/TablesEditor.tsx
- src/components/editors/TablesEditor/components/TableEditor/TableEditor.test.tsx
- src/components/editors/TablesEditor/components/TableEditor/TableEditor.tsx
- src/components/editors/TablesEditor/components/TableEditor/components/ColumnsEditor/ColumnsEditor.tsx
- src/components/editors/TablesEditor/components/TableEditor/components/ColumnsEditor/components/ColumnEditor/ColumnEditor.test.tsx
- src/components/editors/TablesEditor/components/TableEditor/components/ColumnsEditor/components/ColumnEditor/ColumnEditor.tsx
- src/constants.ts
- src/migration.test.ts
- src/migration.ts
- src/types/panel.ts
- src/utils/test.ts
> Add option to hide table header

- CHANGELOG.md
- provisioning/dashboards/panels.json
- src/components/Table/Table.tsx
- src/components/TablePanel/TablePanel.tsx
- src/components/editors/TablesEditor/TablesEditor.tsx
- src/components/editors/TablesEditor/components/TableEditor/TableEditor.test.tsx
- src/components/editors/TablesEditor/components/TableEditor/TableEditor.tsx
- src/constants.ts
- src/migration.test.ts
- src/migration.ts
- src/types/panel.ts
- src/utils/test.ts
Resolves: #121 
Resolves: #145
> Update group expand and collapse behavior 

- CHANGELOG.md
- package.json
- src/components/Table/components/TableRow/TableRow.tsx
> Update wrap column text by word

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/editors/NestedObjectsEditor/components/NestedObjectEditor/components/NestedObjectCardsControl/components/NestedObjectCardsItem/NestedObjectCardsItem.tsx
Await: [PR](https://github.com/VolkovLabs/business-packages/pull/75)
Resolves: #193
> Update packages for Code Editor 

- CHANGELOG.md
- package-lock.json
- package.json
- src/__mocks__/@grafana/ui.tsx
- src/components/Table/components/AggregatedCellRenderer/AggregatedCellRenderer.test.tsx
- src/components/Table/components/TableRow/TableRow.test.tsx
- src/components/TablePanel/TablePanel.styles.ts
- src/components/TablePanel/TablePanel.test.tsx
- src/components/TablePanel/TablePanel.tsx
- src/constants.ts
- src/hooks/useExportData.test.ts
- src/hooks/useExportData.ts
- src/migration.test.ts
- src/migration.ts
- src/module.test.ts
- src/module.ts
- src/types/panel.ts
- src/utils/file.test.ts
- src/utils/file.ts
- src/utils/table.test.ts
- src/utils/test.ts
> Add download settings

- CHANGELOG.md
- package.json
- provisioning/dashboards/data-links.json
- provisioning/dashboards/gauge.json
- provisioning/dashboards/query-based.json
- src/__mocks__/@grafana/ui.tsx
- src/components/Table/components/CellRenderer/components/GaugeCellRenderer/GaugeCellRenderer.styles.ts
- src/components/Table/components/CellRenderer/components/GaugeCellRenderer/GaugeCellRenderer.test.tsx
- src/components/Table/components/CellRenderer/components/GaugeCellRenderer/GaugeCellRenderer.tsx
- src/components/editors/TablesEditor/components/TableEditor/components/ColumnsEditor/components/ColumnEditor/ColumnEditor.test.tsx
- src/components/editors/TablesEditor/components/TableEditor/components/ColumnsEditor/components/ColumnEditor/ColumnEditor.tsx
- src/constants.ts
Per Grafana Panel review
Re: 171068 Plugin Submission
- unexpected error happened 
"Data links" dashboard. 
Edit the first panel "Update Variables".
In the Edit pane, scroll down in "Layout -> List" then expand "device"
- In Grafana 10.3.0  the gauge values are displayed vertically
> Add Table panel review fixes

- src/components/editors/TablesEditor/components/TableEditor/components/ActionsColumnEditor/ActionsColumnEditor.tsx
- src/components/editors/TablesEditor/components/TableEditor/components/ColumnsEditor/components/ColumnEditor/ColumnEditor.tsx
> Update align icons

- provisioning/dashboards/panels.json
- provisioning/dashboards/user-settings.json
- src/components/Table/Table.test.tsx
- src/components/Table/components/DrawerColumnManager/DrawerColumnManage.test.tsx
- src/components/Table/components/TableHeaderCell/TableHeaderCell.tsx
- src/components/TablePanel/TablePanel.test.tsx
- src/components/TablePanel/TablePanel.tsx
- src/migration.test.ts
- src/migration.ts
- src/module.ts
- src/types/panel.ts
- src/utils/test.ts
> Fix E2E test

- CHANGELOG.md
- src/hooks/useTable.test.tsx
- src/hooks/useTable.tsx
> Add fix for background row

- provisioning/dashboards/panels.json
- src/components/Table/Table.tsx
- src/components/Table/hooks/useSyncedColumnFilters.test.ts
- src/components/Table/hooks/useSyncedColumnFilters.ts
- src/utils/table.test.ts
- src/utils/table.ts
> Fix the cleanup action in the ‘live’ filter

- CHANGELOG.md
- provisioning/dashboards/file-loader.json
- src/components/Table/Table.tsx
- src/components/Table/components/CellRenderer/CellRenderer.tsx
- src/components/Table/components/CellRenderer/components/FileCellRenderer/FileCellRenderer.test.tsx
- src/components/Table/components/CellRenderer/components/FileCellRenderer/FileCellRenderer.tsx
- src/components/Table/components/TableRow/TableRow.test.tsx
- src/components/Table/components/TableRow/TableRow.tsx
- src/components/TablePanel/TablePanel.tsx
- src/components/editors/TablesEditor/components/TableEditor/components/ColumnsEditor/components/ColumnEditor/ColumnEditor.test.tsx
- src/components/editors/TablesEditor/components/TableEditor/components/ColumnsEditor/components/ColumnEditor/ColumnEditor.tsx
- src/constants.ts
- src/types/panel.ts
- src/utils/group.ts
> Add file name option for File type cell

- CHANGELOG.md
- package.json
- src/components/Table/Table.tsx
> Fix background color for pinned header

- CHANGELOG.md
- package.json
- provisioning/dashboards/panels.json
- src/components/Table/Table.tsx
- src/components/Table/components/CellRenderer/components/DefaultCellRenderer/DefaultCellRenderer.tsx
- src/components/Table/components/TableRow/TableRow.styles.ts
- src/components/Table/components/TableRow/TableRow.tsx
- src/components/TablePanel/TablePanel.tsx
- src/components/editors/TablesEditor/TablesEditor.tsx
- src/components/editors/TablesEditor/components/TableEditor/TableEditor.test.tsx
- src/components/editors/TablesEditor/components/TableEditor/TableEditor.tsx
- src/constants.ts
- src/migration.test.ts
- src/migration.ts
- src/types/panel.ts
- src/utils/test.ts
> Add option to highlight the row on hover

- CHANGELOG.md
- package.json
- src/utils/table.test.ts
- src/utils/table.ts
> Add support for integer 0-1 Boolean cell type

- CHANGELOG.md
- src/hooks/useExportData.ts
- src/utils/table.test.ts
- src/utils/table.ts
- test/utils/table.ts
Zendesk ticket : https://volkovlabs.zendesk.com/agent/tickets/160
> Add nested objects to table export

- CHANGELOG.md
- provisioning/dashboards/user-settings.json
- src/components/Table/components/TableHeaderCell/TableHeaderCell.test.tsx
- src/components/Table/components/TableHeaderCell/TableHeaderCell.tsx
- src/constants.ts
Zendesk Ticket: https://volkovlabs.zendesk.com/agent/tickets/159
> Combine Filter and Sorting icons when Manager is active

- .config/webpack/webpack.config.ts
- CHANGELOG.md
- package-lock.json
- package.json
- src/components/TablePanel/TablePanel.test.tsx
- src/components/TablePanel/TablePanel.tsx
- src/constants.ts
- src/hooks/useExternalExport.ts
- src/hooks/useUpdateRow.ts
Resolves: #373 
@mikhail-vl 
We already had error handling built in and displayed for all requests.
Also, its handling and error messages are processed correctly.
```js
{!!error && (
<div ref={alertRef} {...TEST_IDS.panel.errorContainer.apply()}>
<AlertWithDetails
details={error}
variant="error"
title="Request error"
onRemove={() => setError('')}
{...TEST_IDS.panel.errorAlertElement.apply()}
/>
</div>
)}
```
```js
const errorMessage = `${operation} Error: ${e instanceof Error && e.message ? e.message : Array.isArray(e) ? e[0] : JSON.stringify(e)}`;
setError(errorMessage);
```
I added an action that scrolls to the top of the panel to the section with the error.
I also added the previously missing tests for this section.
> Improve error handling for Update requests

- CHANGELOG.md
- README.md
- package-lock.json
- package.json
- provisioning/dashboards/devices.json
- src/__mocks__/@volkovlabs/components.tsx
- src/components/Table/components/CellRenderer/components/JsonCellRenderer/JsonCellRenderer.tsx
- src/components/TablePanel/TablePanel.tsx
- src/components/editors/NestedObjectsEditor/NestedObjectsEditor.tsx
- src/components/editors/NestedObjectsEditor/components/NestedObjectEditor/NestedObjectEditor.test.tsx
- src/components/editors/NestedObjectsEditor/components/NestedObjectEditor/NestedObjectEditor.tsx
- src/components/editors/NestedObjectsEditor/components/NestedObjectEditor/components/NestedObjectCardsControl/components/NestedObjectCardsItem/NestedObjectCardsItem.tsx
- src/constants.ts
- src/hooks/useExportData.test.ts
- src/hooks/useExportData.ts
- src/migration.test.ts
- src/types/editor.ts
- src/types/nested-object.ts
- src/utils/export.test.ts
- src/utils/export.ts
- src/utils/table.test.ts
- src/utils/table.ts
- src/utils/test.ts
- test/panel.spec.ts
Zendesk ticket: https://volkovlabs.zendesk.com/agent/tickets/171
> Add handlebars for nested objects
